export interface Product {
  id: string;
  title?: string;
  name?: string;
  nameBn?: string;
  price: number;
  oldPrice?: number;
  compareAtPrice?: number;
  image?: string;
  images?: string[];
  sellerId?: string;
  seller?: string;
  vendorId?: string;
  vendorName?: string;
  rating?: number;
  reviewCount?: number;
  category?: string;
  categoryId?: string;
  categoryName?: string;
  description?: string;
  isFlashSale?: boolean;
  isNewArrival?: boolean;
  isWholesale?: boolean;
  isTrending?: boolean;
  isVerified?: boolean;
  location?: string;
  portal?: 'pk-shop' | 'b2c' | 'wholesale' | 'b2b' | 'retail';
  coinCashback?: number;
  brand?: string;
  stock?: number;
}
