import { NewsArticleType } from './components/NewsCard';

export const MOCK_NEWS_ARTICLES: NewsArticleType[] = [
  {
    id: 'n1',
    title: 'Narayanganj Wholesalers Gear Up for Record Eid Loom Production',
    titleBn: 'রেকর্ড পরিমাণ বিক্রির আশায় নারায়ণগঞ্জের ঐতিহ্যবাহী জামদানী ও সুতা পল্লী',
    summary: 'Loom operators in Narayanganj and Ruhitpur report a 35% surge in wholesale textile bookings ahead of the busy retail trade season.',
    summaryBn: 'আসন্ন উৎসবের মৌসুমকে সামনে রেখে রূপগঞ্জ, আড়াইহাজার ও রুহিতপুরের পাইকারি বাজারে তৈরি পোশাক ও সুতার বিপুল বুকিং সম্পন্ন হয়েছে।',
    content: 'Dhaka and Narayanganj wholesale hubs are seeing unprecedented advance order inquiries. Retailers from Khatunganj, Baburhat, and Chowkbazar have started securing stocks early. Wholesalers are utilizing local digital portals like Paikar Mart to lock in prices and manage direct transport logistics to bypass intermediaries.',
    contentBn: 'আসন্ন উৎসবের বিশাল খুচরা বাজারকে সামনে রেখে দেশের সর্ববৃহৎ পোশাক ও তাঁত পল্লীর পাইকাররা ব্যস্ত সময় পার করছেন। আড়াইহাজার, রূপগঞ্জ ও আউটার ঢাকা রিটেইল মার্কেটগুলোতে প্রতিদিন ৫০ কোটি টাকার বেশি সুতা ও শাড়ি বা কাপড়ের বুকিং হচ্ছে। স্থানীয় পাইকাররা জানালেন, পাইকার মার্ট অ্যাপের ডিজিটাল পেমেন্ট ও ডাইরেক্ট লজিস্টিকস ব্যবহার করায় তাদের খরচ প্রায় ১২% কমেছে, যা ক্রেতাদেরকেও সুলভে প্রোভাইড করার সুযোগ দিচ্ছে।',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    category: 'wholesale',
    categoryLabel: 'Wholesale BD',
    categoryLabelBn: 'পাইকারি সংবাদ',
    source: 'Paikar News Desk',
    author: 'Munna Nirjon',
    publishedAt: 'Today, 10:30 AM',
    readTime: '3 min read',
    readTimeBn: '৩ মিনিট পাঠ',
    views: 1420,
    initialLikes: 85,
    isPremium: true,
  },
  {
    id: 'n2',
    title: 'Jamdani Revival: Export Demands Surge 45% in European Boutiques',
    titleBn: 'ইউরোপের বাজারে ঢাকাই জামদানির রপ্তানি ৪৫% বৃদ্ধি, নতুন দুয়ার',
    summary: 'Direct wholesale partnerships and geographic indicator labels have triggered a majestic wave of interest from global design houses.',
    summaryBn: 'জিআই ট্যাগ এবং ডাইরেক্ট সোশ্যাল কমার্স ইমপোর্টের মাধ্যমে ইউরোপের বিভিন্ন লাক্সারি ফ্যাশন হাউজ সরাসরি তাঁতিদের থেকে পণ্য আমদানি করছে।',
    content: 'Traditional weaves of Sonargaon are receiving direct global patronage. With the introduction of supply chain validation platforms, international buyers can verify authenticity in real-time, drastically reducing counterfeit goods and premium margins flowing away from local weaving visual maestros.',
    contentBn: 'শত বছরের ঐতিহ্য ঢাকাই জামদানির আভিজাত্য এখন দেশের গণ্ডি পেরিয়ে গ্লোবাল কমার্স মার্কেটে নতুন সাড়া ফেলেছে। আন্তর্জাতিক ফ্যাশন কোলাবোরেশনের মাধ্যমে কারিগররা এখন সরাসরি ইউরোপিয়ান বায়ারদের সাথে যুক্ত। এর ফলে মধ্যস্বত্বভোগীদের দৌরাত্ম্য রুখে তাঁতিরা সরাসরি একটি ন্যায্য মূল্য পাচ্ছেন। দেশের কমার্স সেক্টরে এটি এক যুগান্তকারী ও গৌরবময় মাইলফলক।',
    imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&q=80',
    category: 'jamdani',
    categoryLabel: 'Heritage Spot',
    categoryLabelBn: 'জামদানি ঐতিহ্য',
    source: 'Trade Ministry Bulletin',
    author: 'Tarif Hossain',
    publishedAt: 'Yesterday, 4:15 PM',
    readTime: '4 min read',
    readTimeBn: '৪ মিনিট পাঠ',
    views: 2950,
    initialLikes: 231,
  },
  {
    id: 'n3',
    title: 'Local Retailers Witness Shift Toward Social Media Live Purchases',
    titleBn: 'সোশ্যাল কমার্সে তুমুল জোয়ার: ক্রেতারা ঝুঁকছেন লাইভ ভিডিও শপিংয়ে',
    summary: 'Interactive video streaming and direct merchant chats on localized directories dominate Bangladesh retail landscape.',
    summaryBn: 'ভিডিও লাইভ ও সরাসরি সেলার চ্যাটের সুবিধাযুক্ত সোশ্যাল কমার্স প্ল্যাটফর্মগুলোতে বাংলাদেশের সাধারণ খুচরা বিক্রি আশাতীত গতি লাভ করেছে।',
    content: 'Traditional e-commerce is rapidly evolving into interactive experiences. In Dhaka, Chittagong, and Sylhet, 60% of retail transactions inside fashion and electronics are fueled by interactive video-social streams and personal verified chat guarantees.',
    contentBn: 'সাধারণ ওয়েবসাইট থেকে অর্ডার দেওয়ার চাইতে ইন্টারঅ্যাক্টিভ লাইভ ডেমো ভিডিও ও সরাসরি সেলারের সাথে অডিও-ভিডিও চ্যাটিংয়ের মাধ্যমে দেশে খুচরা বাজারে সবচেয়ে বড় বিপ্লব সাধিত হচ্ছে। রিটেইল বিহেভিয়ার বিশ্লেষণ করে দেখা গেছে, লাইভ কমার্সের মাধ্যমে ক্রেতাদের আস্থা বেড়েছে ৮০ শতাংশের বেশি, যা কেনাকাটাকে নিরাপদ ও ঝঞ্ঝাটহীন করেছে।',
    imageUrl: 'https://images.unsplash.com/photo-1491933382434-500287f9b54b?w=600&q=80',
    category: 'retail',
    categoryLabel: 'Retail Trends',
    categoryLabelBn: 'খুচরা কমার্স',
    source: 'BD Tech Insights',
    author: 'Rahima Khatun',
    publishedAt: '3 days ago',
    readTime: '2 min read',
    readTimeBn: '২ মিনিট পাঠ',
    views: 890,
    initialLikes: 46,
  },
  {
    id: 'n4',
    title: 'How SME Entrepreneurs are Utilizing Micro-Logistics to Trim Delivery Time',
    titleBn: 'ক্ষুদ্র উদ্যোক্তাদের লজিস্টিকস বিপ্লব: দ্রুত ও সাশ্রয়ী পণ্য পরিবহন ট্র্যাকিং',
    summary: 'Cooperative shipping structures and intelligent route assignments cut operating costs by 22% for suburban startups.',
    summaryBn: 'সহযোগিতামূলক যৌথ শিপিং কাঠামো ও রিয়েল-টাইম রুট অপ্টিমাইজেশানের ফলে প্রান্তিক ক্ষুদ্র ব্যবসায়ীদের ডেলিভারি খরচ উল্লেখযোগ্যভাবে হ্রাস পেয়েছে।',
    content: 'Suburban small merchants have faced historical hurdles in cost-effective shipping. With automated shared logistics systems, parcel aggregates are routed intelligently, ensuring even remote shops in Jessore, Rangpur, and Feni run optimized standard delivery cycles.',
    contentBn: 'যশোর, রংপুর বা ফেনীর প্রত্যন্ত অঞ্চলের একজন নারী বা ক্ষুদ্র ব্যবসায়ী আগে তাদের তৈরি পণ্য নিয়ে পরিবহন সংকটে পড়তেন। কিন্তু বর্তমানের অটোমেটেড লজিস্টিকস হাব ও রিয়েল টাইমে রাইড-শেয়ার যুক্ত ট্র্যাকিং সিস্টেমগুলোর কারণে তারা একদম সস্তায় সরাসরি ঢাকায় বা দেশের অন্যত্র পার্সেল সরবরাহ করতে পারছেন। এতে প্রান্তিক অর্থনীতি দারুণভাবে বেগবান হচ্ছে।',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80',
    category: 'business',
    categoryLabel: 'SME Secrets',
    categoryLabelBn: 'উদ্যোক্তা গাইড',
    source: 'Paikar Hub Reports',
    author: 'Arif Chowdhury',
    publishedAt: '4 days ago',
    readTime: '5 min read',
    readTimeBn: '৫ মিনিট পাঠ',
    views: 1100,
    initialLikes: 79,
    isPremium: true,
  },
  {
    id: 'n5',
    title: 'Artificial Intelligence and Blockchain in Local Superapps Ecosystem',
    titleBn: 'লোকাল সুপারঅ্যাপে এআই ও ব্লকচেইনের সমন্বয়ে কমার্স ট্রাস্ট বৃদ্ধি',
    summary: 'Intelligent trade recommendations, trust indexes, and smart matching lead automated trading.',
    summaryBn: 'সুপারঅ্যাপে এআই-ভিত্তিক কাস্টমার ট্রেন্ড ও নির্ভরযোগ্যতা সূচক ব্যবহারের ফলে স্বয়ংক্রিয় এবং নিরাপদ কমার্স ট্রানজেকশনে আসছে নতুন বিপ্লব।',
    content: 'Smart super-app models integrate identity security and trade history audits. This creates a transparent rating layer which prevents financial scams and matches buyers to trustworthy suppliers instantly.',
    contentBn: 'পাইকার মার্ট সুপারঅ্যাপে এআই-চালিত স্মার্ট ট্রাস্ট স্কোর এনালাইসিস চালু হওয়ার ফলে ব্যবসা করা আরও নিরাপদ হয়েছে। ক্রেতারা যেকোনো বিক্রেতার প্রোফাইল, ভেরিফাইড পরিচয় এবং অতীত রেকর্ড ১ পলকেই দেখতে পারছেন। এটি কমার্স সেক্টরে প্রতারণা ঠেকাতে দারুণ অবদান রাখবে এবং বিশ্বাসের নতুন রেকর্ড গড়বে।',
    imageUrl: 'https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=600&q=80',
    category: 'tech',
    categoryLabel: 'Trade Tech',
    categoryLabelBn: 'ট্রেড টেক',
    source: 'Dacca Cyber Forum',
    author: 'Dr. Shah Alam',
    publishedAt: '1 week ago',
    readTime: '4 min read',
    readTimeBn: '৪ মিনিট পাঠ',
    views: 1650,
    initialLikes: 102,
  },
  {
    id: 'n6',
    title: 'The Great Jamdani Revival Festivities Showcase Digital Artisans',
    titleBn: 'ঢাকাই ঐতিহ্যবাহী জামদানি মেলায় ডিজিটাল তাঁতিদের বিপুল সাড়া',
    summary: 'Digital storytelling matches rural weavers with global buyers at premium price points.',
    summaryBn: 'অনলাইন স্টোরিটেলিং এবং ডিজিটাল শোরুম প্রর্দশনীর সুবাদে মেলায় প্রত্যন্ত অঞ্চলের তাঁতিরা সরাসরি রেকর্ড সংখ্যক মানুষের কাছে জামদানি বিক্রি করেছেন।',
    content: 'Dhaka National Museum grounds hosted direct weaving showcases. Rural artisans expressed high interest in onboarding with superapps to extend their physical store presence to the online web, bypassing conventional agents completely.',
    contentBn: 'জাতীয় জাদুঘর প্রাঙ্গণে আয়োজিত হয়েছে তিন দিনব্যাপী ঢাকাই জামদানি উৎসব। যেখানে সারা দেশ থেকে আগত শত শত তাঁতি সরাসরি অংশ নেন। এবার সবচেয়ে বিস্ময়কর দিক ছিলো মেলায় অংশ নেওয়া তাঁতিদের নিজস্ব অনলাইন কুইক স্টোর। অফলাইন ক্রেতারা অনলাইনে কিউআর কোড স্ক্যান করে লাইভ কালেকশন দেখে সাথে সাথে ক্যাশলেস ডেলিভারি বুকিং করেছেন, যা মেলাকে অভূতপূর্ব রূপ দিয়েছে।',
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80',
    category: 'jamdani',
    categoryLabel: 'Heritage Spot',
    categoryLabelBn: 'জামদানি ঐতিহ্য',
    source: 'Bangladesh Cultural Board',
    author: 'Sultana Begum',
    publishedAt: '1 week ago',
    readTime: '3 min read',
    readTimeBn: '৩ মিনিট পাঠ',
    views: 2310,
    initialLikes: 198,
  }
];
